/* automatically generated by rust-bindgen 0.72.1 */
#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vec {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mat33 {
    pub m: [[f32; 3usize]; 3usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union Axis3f {
    pub __bindgen_anon_1: Axis3f__bindgen_ty_1,
    pub axis: [f32; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Axis3f__bindgen_ty_1 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}
#[doc = " Attitude in euler angle form"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct attitude_s {
    pub timestamp: u32,
    pub roll: f32,
    pub pitch: f32,
    pub yaw: f32,
}
#[doc = " Attitude in euler angle form"]
pub type attitude_t = attitude_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vec3_s {
    pub timestamp: u32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
}
pub type point_t = vec3_s;
pub type velocity_t = vec3_s;
pub type acc_t = vec3_s;
pub type jerk_t = vec3_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct quaternion_s {
    pub __bindgen_anon_1: quaternion_s__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union quaternion_s__bindgen_ty_1 {
    pub __bindgen_anon_1: quaternion_s__bindgen_ty_1__bindgen_ty_1,
    pub __bindgen_anon_2: quaternion_s__bindgen_ty_1__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct quaternion_s__bindgen_ty_1__bindgen_ty_1 {
    pub q0: f32,
    pub q1: f32,
    pub q2: f32,
    pub q3: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct quaternion_s__bindgen_ty_1__bindgen_ty_2 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub w: f32,
}
pub type quaternion_t = quaternion_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct baro_s {
    pub pressure: f32,
    pub temperature: f32,
    pub asl: f32,
}
pub type baro_t = baro_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct sensorData_s {
    pub acc: Axis3f,
    pub gyro: Axis3f,
    pub mag: Axis3f,
    pub baro: baro_t,
    pub interruptTimestamp: u64,
}
pub type sensorData_t = sensorData_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct state_s {
    pub attitude: attitude_t,
    pub attitudeQuaternion: quaternion_t,
    pub position: point_t,
    pub velocity: velocity_t,
    pub acc: acc_t,
}
pub type state_t = state_s;
pub const control_mode_e_controlModeLegacy: control_mode_e = 0;
pub const control_mode_e_controlModeForceTorque: control_mode_e = 1;
pub const control_mode_e_controlModeForce: control_mode_e = 2;
pub type control_mode_e = ::core::ffi::c_uint;
pub use self::control_mode_e as control_mode_t;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct control_s {
    pub __bindgen_anon_1: control_s__bindgen_ty_1,
    pub controlMode: control_mode_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union control_s__bindgen_ty_1 {
    pub __bindgen_anon_1: control_s__bindgen_ty_1__bindgen_ty_1,
    pub __bindgen_anon_2: control_s__bindgen_ty_1__bindgen_ty_2,
    pub normalizedForces: [f32; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct control_s__bindgen_ty_1__bindgen_ty_1 {
    pub roll: i16,
    pub pitch: i16,
    pub yaw: i16,
    pub thrust: f32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct control_s__bindgen_ty_1__bindgen_ty_2 {
    pub thrustSi: f32,
    pub __bindgen_anon_1: control_s__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union control_s__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1 {
    pub torque: [f32; 3usize],
    pub __bindgen_anon_1: control_s__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct control_s__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1__bindgen_ty_1 {
    pub torqueX: f32,
    pub torqueY: f32,
    pub torqueZ: f32,
}
pub type control_t = control_s;
pub const mode_e_modeDisable: mode_e = 0;
pub const mode_e_modeAbs: mode_e = 1;
pub const mode_e_modeVelocity: mode_e = 2;
pub type mode_e = ::core::ffi::c_uint;
pub use self::mode_e as stab_mode_t;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct setpoint_s {
    pub timestamp: u32,
    pub attitude: attitude_t,
    pub attitudeRate: attitude_t,
    pub attitudeQuaternion: quaternion_t,
    pub thrust: f32,
    pub position: point_t,
    pub velocity: velocity_t,
    pub acceleration: acc_t,
    pub jerk: jerk_t,
    pub velocity_body: bool,
    pub mode: setpoint_s__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct setpoint_s__bindgen_ty_1 {
    pub x: stab_mode_t,
    pub y: stab_mode_t,
    pub z: stab_mode_t,
    pub roll: stab_mode_t,
    pub pitch: stab_mode_t,
    pub yaw: stab_mode_t,
    pub quat: stab_mode_t,
}
pub type setpoint_t = setpoint_s;
unsafe extern "C" {
    pub fn controllerOutOfTreeInit();
}
unsafe extern "C" {
    pub fn controllerOutOfTreeTest() -> bool;
}
unsafe extern "C" {
    pub fn controllerOutOfTree(
        control: *mut control_t,
        setpoint: *const setpoint_t,
        sensors: *const sensorData_t,
        state: *const state_t,
        tick: u32,
    );
}
